import{S as l,i as f}from"./assets/vendor-BrddEoy-.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const a of t.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&n(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function n(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const u="https://pixabay.com/api/",m="46859075-3fccd495eb65e9407cc96c329";async function d(r,o=1,s=12){const n=`${u}?key=${m}&q=${encodeURIComponent(r)}&image_type=photo&orientation=horizontal&safesearch=true&per_page=${s}&page=${o}`;try{const e=await fetch(n);if(!e.ok)throw new Error("Failed to fetch images");return await e.json()}catch(e){throw console.error("Error fetching images:",e),e}}const c=document.querySelector(".gallery");function p(r){c.innerHTML=r.map(g).join(""),new l(".gallery a").refresh()}function g(r){return`
    <a href="${r.largeImageURL}" class="gallery_item">
      <img src="${r.webformatURL}" alt="${r.tags}" class="gallery_image" width="380"/>
      <div class="info">
        <p class="info-item"><b>Likes:</b> ${r.likes}</p>
        <p class="info-item"><b>Views:</b> ${r.views}</p>
        <p class="info-item"><b>Comments:</b> ${r.comments}</p>
        <p class="info-item"><b>Downloads:</b> ${r.downloads}</p>
      </div>
    </a>
  `}function y(){f.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!"})}function h(){c.innerHTML=""}const b=document.querySelector(".loader"),w=document.querySelector(".form");w.addEventListener("submit",L);async function L(r){r.preventDefault();const o=r.currentTarget.elements.query.value.trim();if(!o){iziToast.error({title:"Error",message:"Please enter a search term."});return}h(),i(!0);try{const s=await d(o);s.hits.length===0?y():p(s.hits)}catch{iziToast.error({title:"Error",message:"Something went wrong. Please try again!"})}finally{i(!1)}}function i(r){b.style.display=r?"block":"none"}
//# sourceMappingURL=index.js.map
